# От ВДело к ВДело

POST {{URL}}/bank/identification
Content-Type: application/json

{
    "bankId": 2,
    "uuid": "{{$uuid}}",
    "transaction_uid": "{{$uuid}}",
    "transaction_date": "2022-02-25 08:11:43.560000+00:00",
    "payment_destination": "Заемщик ИНН 690300870030, возврат средств по дог. ИНВ-20230406/2071 ИП Сметанникова Л.В., основание дог. инкассо-цессии, правила пользования ИП \"ВДЕЛО\" ред.15 (от суммы 50 000= удерж. госпош. 24 525=), Без НДС",
    "amount": 25000,
    "name": "ООО \"ВДЕЛО\"",
    "inn": "6623134596",
    "kpp": "",
    "account": "40702810601500076453",
    "bik": "044525104",
    "meta": {
        "operationId": "{{$uuid}}",
        "id": "10",
        "date": "2025-01-10",
        "amount": 25000,
        "drawDate": "2025-01-10",
        "payerName": "ООО \"ВДЕЛО\"",
        "payerInn": "6623134596",
        "payerAccount": "40702810601500076453",
        "payerCorrAccount": "30101810745374525104",
        "payerBic": "044525104",
        "payerBank": "ООО \"Банк Точка\"",
        "chargeDate": "2025-01-10",
        "recipient": "ООО \"ВДЕЛО\"",
        "recipientInn": "6623134596",
        "recipientAccount": "40701810300000006947",
        "recipientCorrAccount": "30101810145250000974",
        "recipientBic": "044525974",
        "recipientBank": "АО \"ТБанк\"",
        "operationType": "01",
        "paymentPurpose": "Заемщик ИНН 690300870030, возврат средств по дог. ИНВ-20230406/2071 ИП Сметанникова Л.В., основание дог. инкассо-цессии, правила пользования ИП \"ВДЕЛО\" ред.15 (от суммы 50 000= удерж. госпош. 24 525=), Без НДС",
        "creatorStatus": "",
        "executionOrder": "5"
    }
  }
